img = 0
img2 = 0
drawing = 0
value = 0
mask = 0
rectangle = 0
rect = 0
rect_or_mask = 0
ix = 0
iy = 0
rect_over = 0
RED = [0, 0, 255]
GREEN = [0, 255, 0]
BLUE = [255, 0, 0]
BLACK = [0, 0, 0]
WHITE = [255, 255, 255]
Draw_BackGround = {'color': BLACK, 'val': 0}
Draw_ForeGround = {'color': WHITE, 'val': 1}
Draw_PR_BackGround = {'color': GREEN, 'val': 2}
Draw_PR_ForeGround = {'color': RED, 'val': 3}
rect = (0, 0, 1, 1)
drawing = False
rectangle = False
rect_over = False
rect_or_mask = 100
value = Draw_ForeGround
thickness = 3